{% set name = "magics-python" %}
{% set pypi_name = "Magics" %}
{% set version = "1.0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: c007192f4bc868350af77e83987dc7f84ef4968159e9ab30358e9df31d0b0987

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - numpy
    - python

test:
  commands:
    - test -f $(python -c "import site; print(site.getsitepackages()[0])")/Magics/__init__.py  # [not win]

about:
  home: https://github.com/ecmwf/magics-python
  license: Apache 2.0
  license_family: Apache
  summary: Python interface to plot meteorological data in GRIB, NetCDF and BUFR.

extra:
  recipe-maintainers:
    - dtip
    - StephanSiemen
