travis:
  secure:
    BINSTAR_TOKEN: TPjKpbAnRPe3D8IN1dIE78Q2DQ0SixSd1DIDtORV/ZoJbraubJ9YbYddPtr6tGhnZIXWkN5+LzVs6cGI9QsoCzTYUYakHJ+PdIvXS11dBNByzFvTrkrPphVS9PBtll8bb4u9qk029keJMRWxw21T6Q9rLDneQ4THjUNekrO4eVyQ5eQNNsPQSQfBsp0ECFRMCJKUzCw0flqVGATleOdeb6F300zJEkd5n26s0C1aed2Dlq1jraKSFYfn/DBuCTpsz39nEwmfWHJRrrFGqpTB0s64XJxD/sWqRnP8P4i1qOnC0aXiSHksbQ1zKB5ktAyRZDFZTMNjJqq3GfpI5VhUdQo2zTrvtc8Z9aVPmHJEt7Jtma9aOD0Njr10UcqSnMcwpXHszu4N59yR577qP8eKaUV5fyzH8KMGFZJc/zZk3VZKBgek/CgS1X4igdksOdB2m6tR8y+n38d+8d9qXN7Dek1Xf1ZFy5cPsbiubZhlPkWuq1qUIvNuoeZRf91behukpnTCb3RKheOjgi0NLrL3VUKw6jhNQK097P9f/9hHa3HQb5dkwdS/Hwmdo7XdO/Or3XCDNilaUtaYL9RtPW8ZY0O5PQq3T9Q62TnEn/MAWNuSwfWbpEEDXM+as8cAYkfovYXeUqEBNW3opyfLrYGGfIjTs8w7BN7VofWp/use7h8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
